In [ ]:
%pip install mlxtend --upgrade

In [ ]:
!pip install apyori
# !pip install mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

In [ ]:
import numpy as np
import matplotlib.pyplot as mtp  
import pandas as pd  


import apyori

### Read Data

In [ ]:
store_data = pd.read_csv("store_data.csv", header=None)
display(store_data.head())
print(store_data.shape)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(7501, 20)

In [ ]:
records = []
for row in store_data.itertuples():
  records.append(np.array([str(x).strip() for x in list(row[1:]) if x not in [np.NaN]]))

In [ ]:
for x in records[56:60]:
  print(x)

['turkey' 'fresh tuna' 'frozen vegetables' 'tomatoes' 'ground beef'
 'spaghetti' 'mineral water' 'chocolate' 'soup' 'milk' 'olive oil']
['eggs' 'cookies']
['soup' 'chicken' 'gums' 'soda' 'body spray' 'energy drink' 'green tea']
['turkey' 'frozen vegetables' 'mineral water' 'cider' 'cooking oil'
 'green tea']

## Apriori Algorithm

In [ ]:
association_rules = apyori.apriori(records, min_support=0.0035, min_confidence=0.1, min_lift=2, min_length=2)
association_results = list(association_rules)

In [ ]:
print("There are {} Relation derived.".format(len(association_results)))

There are 293 Relation derived.

### Frequent Itemsets

In [ ]:
print("DERIVED FREQUENT ITEMSETS")
for i in range(0, 20):
    print(association_results[i][0])

DERIVED FREQUENT ITEMSETS
frozenset({'burgers', 'almonds'})
frozenset({'avocado', 'frozen smoothie'})
frozenset({'avocado', 'soup'})
frozenset({'black tea', 'milk'})
frozenset({'body spray', 'french fries'})
frozenset({'burgers', 'french wine'})
frozenset({'burgers', 'ham'})
frozenset({'chicken', 'butter'})
frozenset({'fresh tuna', 'cake'})
frozenset({'cereals', 'milk'})
frozenset({'cooking oil', 'chicken'})
frozenset({'fresh bread', 'chicken'})
frozenset({'chicken', 'light cream'})
frozenset({'tomato sauce', 'chocolate'})
frozenset({'eggs', 'cider'})
frozenset({'cooking oil', 'grated cheese'})
frozenset({'cooking oil', 'herb & pepper'})
frozenset({'soup', 'cooking oil'})
frozenset({'frozen smoothie', 'cottage cheese'})
frozenset({'mushroom cream sauce', 'escalope'})

### Derived Association Rules

In [ ]:
association_dict = {"Rule":[],"Antecedant":[],"Precedent":[],"Support":[],"Confidence":[],"Lift":[]}

for item in association_results:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    # print("Rule: " + items[0] + " -> " + items[1])
    association_dict["Rule"].append(f"{items[0]} => {items[1]}")
    association_dict["Antecedant"].append(items[0])
    association_dict["Precedent"].append(items[1])
    

    # second index of the inner list
    # print("Support: " + str(item[1]))
    association_dict["Support"].append(str(item[1]))

    # third index of the list located at 0th
    # of the third index of the inner list

    # print("Confidence: " + str(item[2][0][2]))
    # association_results["Confidence"].append(str(item[2][0][2]))
    # print("Lift: " + str(item[2][0][3]))
    association_dict["Lift"].append(str(item[2][0][2]))
    association_dict["Confidence"].append(str(item[2][0][3]))
    # print("=====================================")
  
assoc_df = pd.DataFrame(association_dict)
assoc_df.head()

,Rule,Antecedant,Precedent,Support,Confidence,Lift
0,burgers => almonds,burgers,almonds,0.005199306759098787,2.923577382023146,0.25490196078431376
1,avocado => frozen smoothie,avocado,frozen smoothie,0.005065991201173177,2.4003200000000002,0.152
2,avocado => soup,avocado,soup,0.004399413411545127,2.6124854881266493,0.132
3,black tea => milk,black tea,milk,0.004266097853619517,2.3079112341833006,0.29906542056074764
4,body spray => french fries,body spray,french fries,0.004266097853619517,2.17712150346479,0.37209302325581395

In [ ]:
print("Number of rules created for each Product Bought")
assoc_df.groupby("Antecedant")["Rule"].count().sort_values()

Number of rules created for each Product Bought

Antecedant
black tea                1
body spray               1
tomato juice             1
strong cheese            1
rice                     1
mushroom cream sauce     1
escalope                 1
fresh bread              1
avocado                  2
meatballs                2
hot dogs                 2
grated cheese            2
frozen smoothie          2
whole wheat rice         2
cookies                  2
cereals                  2
chicken                  2
cooking oil              3
tomato sauce             3
french fries             4
low fat yogurt           4
fresh tuna               4
frozen vegetables        5
turkey                   6
whole wheat pasta        6
pancakes                 7
ground beef              7
shrimp                  10
soup                    16
burgers                 20
chocolate               29
olive oil               29
spaghetti               33
mineral water           38
eggs                    43
Name: Rule, dtype: int64

In [ ]:
# possible prediction
def predict_possible(purchased_product):
  return assoc_df[assoc_df["Antecedant"] == purchased_product].sort_values(["Confidence"])


res_df = predict_possible("frozen vegetables")
res_df

,Rule,Antecedant,Precedent,Support,Confidence,Lift
168,frozen vegetables => milk,frozen vegetables,milk,0.005732568990801226,2.3205200149644596,0.3006993006993007
29,frozen vegetables => tomatoes,frozen vegetables,tomatoes,0.0161311825089988,2.4744639376218323,0.1692307692307692
190,frozen vegetables => milk,frozen vegetables,milk,0.0041327822956939075,2.560885893327166,0.1751412429378531
181,frozen vegetables => ground beef,frozen vegetables,ground beef,0.005732568990801226,2.612868993227698,0.3385826771653543
27,frozen vegetables => parmesan cheese,frozen vegetables,parmesan cheese,0.005465937874950006,2.886760219646125,0.27516778523489926

## FPTree Algorithm

In [ ]:
transaction = clean_data.copy()

In [ ]:
# Transform Every Transaction to Seperate List & Gather Them into Numpy Array
# transaction = []
# for i in range(dataset.shape[0]):
#     transaction.append([str(dataset.values[i,j]) for j in range(dataset.shape[1])])

# # creating the numpy array of the transactions
# transaction = np.array(transaction)

# importing the required module
from mlxtend.preprocessing import TransactionEncoder

# initializing the transactionEncoder
te = TransactionEncoder()
te_ary = te.fit(transaction).transform(transaction)
dataset = pd.DataFrame(te_ary, columns=te.columns_)

# dataset after encoded
dataset.head()

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

#### We want to form rules using only top `k` features not 121

In [ ]:
# select top 30 items
top_product_names = ['almonds', 'antioxydant juice', 'asparagus', 'avocado',
       'babies food', 'bacon', 'barbecue sauce', 'black tea', 'blueberries','turkey', 'vegetables mix', 'water spray', 'white wine',
       'whole weat flour', 'whole wheat pasta', 'whole wheat rice', 'yams',
       'yogurt cake', 'zucchini']

processed_dataset = dataset.copy()
# processed_dataset = dataset[top_product_names] 
processed_dataset.shape

(7501, 119)

#### Apply FPGrowth

In [ ]:
#Importing Libraries
from mlxtend.frequent_patterns import fpgrowth

#running the fpgrowth algorithm
res=fpgrowth(processed_dataset,min_support=0.005, use_colnames=True)

print(f"Extracted {len(res)} frequent itemsets")
# printing top 10
res.head(10)

Extracted 725 frequent itemsets

    support           itemsets
0  0.238368    (mineral water)
1  0.132116        (green tea)
2  0.076523   (low fat yogurt)
3  0.071457           (shrimp)
4  0.065858        (olive oil)
5  0.063325  (frozen smoothie)
6  0.047460            (honey)
7  0.042528           (salmon)
8  0.033329          (avocado)
9  0.031862   (cottage cheese)

#### Check Association Rules

In [ ]:
# importing required module
from mlxtend.frequent_patterns import association_rules

# creating asssociation rules
assoc_rules=association_rules(res, metric="lift", min_threshold=2)
assoc_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(frozen vegetables),(shrimp),0.095321,0.071457,0.016664,0.174825,2.446574,0.009853,1.125268
1,(shrimp),(frozen vegetables),0.071457,0.095321,0.016664,0.233209,2.446574,0.009853,1.179825
2,"(chocolate, mineral water)",(shrimp),0.052660,0.071457,0.007599,0.144304,2.019445,0.003836,1.085131
3,(shrimp),"(chocolate, mineral water)",0.071457,0.052660,0.007599,0.106343,2.019445,0.003836,1.060072
4,"(chocolate, spaghetti)",(shrimp),0.039195,0.071457,0.006399,0.163265,2.284800,0.003598,1.109722
...,...,...,...,...,...,...,...,...,...
477,(light mayo),(pancakes),0.027196,0.095054,0.005466,0.200980,2.114381,0.002881,1.132570
478,(mushroom cream sauce),(escalope),0.019064,0.079323,0.005733,0.300699,3.790833,0.004220,1.316568
479,(escalope),(mushroom cream sauce),0.079323,0.019064,0.005733,0.072269,3.790833,0.004220,1.057349
480,(mineral water),(nonfat milk),0.238368,0.010399,0.005066,0.021253,2.043811,0.002587,1.011090
481,(nonfat milk),(mineral water),0.010399,0.238368,0.005066,0.487179,2.043811,0.002587,1.485182

### Get predictions

In [ ]:
def get_pred_fpgrowth(products, assoc_rules):  
  return assoc_rules[assoc_rules["antecedents"]==frozenset(products)].sort_values(["confidence"])

bought_products = ["shrimp"]
res = get_pred_fpgrowth(bought_products, assoc_rules)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
354,(shrimp),(pasta),0.071457,0.015731,0.005066,0.070896,4.506672,0.003942,1.059374
31,(shrimp),"(chocolate, frozen vegetables)",0.071457,0.022930,0.005333,0.074627,3.254512,0.003694,1.055866
16,(shrimp),"(chocolate, milk)",0.071457,0.032129,0.005466,0.076493,2.380791,0.003170,1.048038
26,(shrimp),"(spaghetti, frozen vegetables)",0.071457,0.027863,0.005999,0.083955,3.013149,0.004008,1.061233
38,(shrimp),"(spaghetti, ground beef)",0.071457,0.039195,0.005999,0.083955,2.142000,0.003198,1.048863
7,(shrimp),"(chocolate, spaghetti)",0.071457,0.039195,0.006399,0.089552,2.284800,0.003598,1.055311
21,(shrimp),"(mineral water, frozen vegetables)",0.071457,0.035729,0.007199,0.100746,2.819768,0.004646,1.072302
3,(shrimp),"(chocolate, mineral water)",0.071457,0.052660,0.007599,0.106343,2.019445,0.003836,1.060072
12,(shrimp),"(mineral water, milk)",0.071457,0.047994,0.007866,0.110075,2.293527,0.004436,1.069760
312,(shrimp),(tomatoes),0.071457,0.068391,0.011199,0.156716,2.291481,0.006311,1.104740
1,(shrimp),(frozen vegetables),0.071457,0.095321,0.016664,0.233209,2.446574,0.009853,1.179825

## Apriori using MLExtend

In [ ]:
clean_data = []
for row in store_data.itertuples():
  clean_data.append(np.array([str(x).strip() for x in list(row[1:]) if x not in [np.NaN]]))

In [ ]:
clean_data[0]

array(['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes',
       'whole weat flour', 'yams', 'cottage cheese', 'energy drink',
       'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad',
       'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie',
       'spinach', 'olive oil'], dtype='<U17')

In [ ]:
# clean_data = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
#            ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
#            ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
#            ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
#            ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

te = TransactionEncoder()
te_try = te.fit(clean_data).transform(clean_data)

transformed_df = pd.DataFrame(te_try, columns=te.columns_)
transformed_df.head(5)

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
frequent_itemsets = apriori(transformed_df, min_support=0.005, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

      support                                      itemsets  length
0    0.020397                                     (almonds)       1
1    0.008932                           (antioxydant juice)       1
2    0.033329                                     (avocado)       1
3    0.008666                                       (bacon)       1
4    0.010799                              (barbecue sauce)       1
..        ...                                           ...     ...
720  0.007466              (soup, spaghetti, mineral water)       3
721  0.009332          (spaghetti, mineral water, tomatoes)       3
722  0.006399            (turkey, spaghetti, mineral water)       3
723  0.006266  (whole wheat rice, spaghetti, mineral water)       3
724  0.005066              (olive oil, pancakes, spaghetti)       3

[725 rows x 3 columns]

In [ ]:
# length =2 and Support Count = 0.8
frequent_itemsets[ (frequent_itemsets['length'] == 2)]

      support                        itemsets  length
101  0.005199              (burgers, almonds)       2
102  0.005999            (chocolate, almonds)       2
103  0.006532                 (eggs, almonds)       2
104  0.005066            (almonds, green tea)       2
105  0.005199                 (almonds, milk)       2
..        ...                             ...     ...
547  0.008799  (whole wheat pasta, spaghetti)       2
548  0.014131   (whole wheat rice, spaghetti)       2
549  0.006532              (turkey, tomatoes)       2
550  0.005999    (whole wheat rice, tomatoes)       2
551  0.007066      (turkey, whole wheat rice)       2

[451 rows x 3 columns]

#### Check Association Rules - Size =2

In [ ]:
# importing required module
from mlxtend.frequent_patterns import association_rules

# assoc_rules=association_rules(frequent_itemsets, metric="lift", min_threshold=2)
assoc_rules=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
assoc_rules["antecedent_len"] = assoc_rules["antecedents"].apply(lambda x: len(x))
assoc_rules["consequents_len"] = assoc_rules["consequents"].apply(lambda x: len(x))
assoc_rules

# assoc_rules[(assoc_rules.consequents_len==1) & (assoc_rules.antecedent_len==1)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequents_len
0,"(chocolate, chicken)",(mineral water),0.014665,0.238368,0.007599,0.518182,2.173871,0.004103,1.580745,2,1
1,"(olive oil, chocolate)",(mineral water),0.016398,0.238368,0.008266,0.504065,2.114649,0.004357,1.535749,2,1
2,"(chocolate, soup)",(mineral water),0.010132,0.238368,0.005599,0.552632,2.318395,0.003184,1.702471,2,1
3,"(eggs, cooking oil)",(mineral water),0.011732,0.238368,0.006399,0.545455,2.288286,0.003603,1.675590,2,1
4,"(eggs, ground beef)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,0.005365,1.543848,2,1
5,"(frozen vegetables, ground beef)",(mineral water),0.016931,0.238368,0.009199,0.543307,2.279277,0.005163,1.667711,2,1
6,"(frozen vegetables, ground beef)",(spaghetti),0.016931,0.174110,0.008666,0.511811,2.939582,0.005718,1.691742,2,1
7,"(olive oil, frozen vegetables)",(mineral water),0.011332,0.238368,0.006532,0.576471,2.418404,0.003831,1.798297,2,1
8,"(soup, frozen vegetables)",(mineral water),0.007999,0.238368,0.005066,0.633333,2.656954,0.003159,2.077178,2,1
9,"(olive oil, frozen vegetables)",(spaghetti),0.011332,0.174110,0.005733,0.505882,2.905531,0.003760,1.671444,2,1
10,"(ground beef, milk)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,0.005822,1.532552,2,1
11,"(pancakes, ground beef)",(mineral water),0.014531,0.238368,0.007466,0.513761,2.155327,0.004002,1.566375,2,1
12,"(soup, ground beef)",(mineral water),0.009732,0.238368,0.005066,0.520548,2.183798,0.002746,1.588546,2,1
13,"(shrimp, ground beef)",(spaghetti),0.011465,0.174110,0.005999,0.523256,3.005315,0.004003,1.732354,2,1
14,"(olive oil, milk)",(mineral water),0.017064,0.238368,0.008532,0.500000,2.097595,0.004465,1.523264,2,1
15,"(soup, milk)",(mineral water),0.015198,0.238368,0.008532,0.561404,2.355194,0.004909,1.736520,2,1
16,"(turkey, milk)",(mineral water),0.011332,0.238368,0.006133,0.541176,2.270338,0.003431,1.659967,2,1
17,"(olive oil, soup)",(mineral water),0.008932,0.238368,0.005199,0.582090,2.441976,0.003070,1.822476,2,1
18,"(spaghetti, salmon)",(mineral water),0.013465,0.238368,0.006799,0.504950,2.118363,0.003589,1.538496,2,1
19,"(soup, spaghetti)",(mineral water),0.014265,0.238368,0.007466,0.523364,2.195614,0.004065,1.597933,2,1